#!/usr/bin/env python3
"""Create per-controller group plots from existing raw evaluation CSV files.

This script does not run any SUMO evaluations. It rebuilds the
`*_queue_by_group.png` and `*_speed_by_group.png` figures directly from
`*_queue_raw.csv` and `*_speed_raw.csv` files generated by
`eval_signal_controllers.py`.

Example:
    python3 plot_groups_per_controller.py
    python3 plot_groups_per_controller.py --controllers iqll_marl,iqll_retrained
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import shutil
import subprocess
import warnings
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

_MPLCONFIGDIR = Path("/tmp/matplotlib")
_MPLCONFIGDIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(_MPLCONFIGDIR))

import matplotlib as mpl

mpl.use("Agg")


def _tex_package_available(package_name: str) -> bool:
    kpsewhich = shutil.which("kpsewhich")
    if not kpsewhich:
        return False
    result = subprocess.run(
        [kpsewhich, package_name],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        check=False,
    )
    return bool(result.stdout.strip())


def _configure_plot_style() -> None:
    params = {
        "text.usetex": True,
        "text.latex.preamble": r"\usepackage{newtxtext}\usepackage{newtxmath}",
        "font.family": "serif",
        "font.size": 18,
        "axes.labelsize": 18,
        "axes.titlesize": 18,
        "xtick.labelsize": 17,
        "ytick.labelsize": 17,
        "legend.fontsize": 16,
        "figure.titlesize": 20,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }

    missing_bins = [exe for exe in ("latex", "kpsewhich", "dvipng") if shutil.which(exe) is None]
    required_sty = ("newtxtext.sty", "newtxmath.sty", "type1ec.sty")
    missing_sty = [sty for sty in required_sty if not _tex_package_available(sty)]

    if missing_bins or missing_sty:
        params["text.usetex"] = False
        params.pop("text.latex.preamble", None)
        warnings.warn(
            "Falling back to Matplotlib text rendering because TeX dependencies are missing. "
            "Missing executables: %s. Missing TeX packages: %s."
            % (missing_bins or "none", missing_sty or "none"),
            RuntimeWarning,
        )

    mpl.rcParams.update(params)


_configure_plot_style()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_INPUT_DIR = PROJECT_ROOT / "runs_eval" / "signal_controller_benchmark"
DEFAULT_OUTPUT_DIR = DEFAULT_INPUT_DIR

RAW_PATTERN = re.compile(
    r"^(?P<controller>[a-z0-9_]+)_group(?P<group_index>\d+)_(?P<group_slug>[a-z0-9_]+)_(?P<metric>queue|speed)_raw\.csv$"
)

TOKEN_LABELS = {
    "ia2c": "IA2C",
    "ma2c": "MA2C",
    "iqll": "IQL-LR",
    "ppo": "PPO",
    "marl": "MARL",
    "retrained": "Retrained",
}


@dataclass(frozen=True)
class RawSeriesFile:
    controller: str
    family: str
    group_index: int
    group_slug: str
    metric: str
    path: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help="Directory containing raw eval CSV files and optional manifest CSVs.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory to save generated plots (family subfolders are preserved).",
    )
    parser.add_argument(
        "--controllers",
        type=str,
        default="",
        help="Optional comma-separated list of controller names to plot.",
    )
    return parser.parse_args()


def _read_controller_manifest(manifest_path: Path) -> Dict[str, Dict[str, str]]:
    if not manifest_path.exists():
        return {}
    lookup: Dict[str, Dict[str, str]] = {}
    with manifest_path.open("r", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            name = (row.get("controller") or "").strip()
            if not name:
                continue
            lookup[name] = {
                "label": (row.get("controller_label") or "").strip(),
                "family": (row.get("family") or "").strip(),
                "variant": (row.get("variant") or "").strip(),
            }
    return lookup


def _read_demand_manifest(manifest_path: Path) -> Dict[int, str]:
    if not manifest_path.exists():
        return {}
    lookup: Dict[int, str] = {}
    with manifest_path.open("r", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            raw_idx = (row.get("group_index") or "").strip()
            raw_name = (row.get("group_name") or "").strip()
            if not raw_idx or not raw_name:
                continue
            try:
                idx = int(raw_idx)
            except ValueError:
                continue
            lookup[idx] = raw_name
    return lookup


def _discover_raw_series(input_dir: Path) -> List[RawSeriesFile]:
    if not input_dir.exists():
        raise FileNotFoundError("Input directory does not exist: %s" % input_dir)

    discovered: List[RawSeriesFile] = []
    for path in sorted(input_dir.rglob("*_raw.csv")):
        if path.name.startswith(".~lock."):
            continue
        match = RAW_PATTERN.match(path.name)
        if not match:
            continue
        discovered.append(
            RawSeriesFile(
                controller=match.group("controller"),
                family=path.parent.name,
                group_index=int(match.group("group_index")),
                group_slug=match.group("group_slug"),
                metric=match.group("metric"),
                path=path,
            )
        )

    if not discovered:
        raise FileNotFoundError(
            "No raw queue/speed CSV files found under %s" % input_dir
        )
    return discovered


def _resolve_selected_controllers(all_controllers: Iterable[str], selected_arg: str) -> List[str]:
    available = sorted(set(all_controllers))
    if not selected_arg.strip():
        return available

    requested = [token.strip() for token in selected_arg.split(",") if token.strip()]
    unknown = [name for name in requested if name not in available]
    if unknown:
        raise ValueError(
            "Unknown controllers: %s. Available: %s"
            % (", ".join(unknown), ", ".join(available))
        )
    return requested


def _prettify_controller_name(controller: str) -> str:
    words = []
    for token in controller.split("_"):
        if token in TOKEN_LABELS:
            words.append(TOKEN_LABELS[token])
        elif token.isdigit():
            words.append(token)
        else:
            words.append(token.upper() if len(token) <= 3 else token.title())
    return " ".join(words)


def _label_for_controller(controller: str, controller_manifest: Dict[str, Dict[str, str]]) -> str:
    manifest_row = controller_manifest.get(controller, {})

    family = manifest_row.get("family", "").strip().lower()
    if not family:
        family = controller.split("_", 1)[0].lower()
    family_label = TOKEN_LABELS.get(family, family.upper())

    variant = manifest_row.get("variant", "").strip().lower()
    if not variant:
        if controller.endswith("_retrained"):
            variant = "retrained"
        elif controller.endswith("_marl"):
            variant = "baseline"

    if variant == "baseline":
        return "Baseline %s" % family_label
    if variant == "retrained":
        return "DR-%s" % family_label

    return _prettify_controller_name(controller)


def _family_for_controller(
    controller: str,
    files: List[RawSeriesFile],
    controller_manifest: Dict[str, Dict[str, str]],
) -> str:
    manifest_row = controller_manifest.get(controller, {})
    family = manifest_row.get("family", "").strip()
    if family:
        return family

    families = [item.family for item in files if item.controller == controller]
    if not families:
        return "misc"
    return Counter(families).most_common(1)[0][0]


def _metric_title(controller_label: str, metric: str) -> str:
    if metric == "queue":
        return "%s - Total Queue by Demand Group" % controller_label
    return "%s - Average Speed by Demand Group" % controller_label


def _metric_ylabel(metric: str) -> str:
    if metric == "queue":
        return "Total queued vehicles (veh)"
    return "Average speed (m/s)"


def _load_mean_series(csv_path: Path) -> Tuple[np.ndarray, np.ndarray]:
    df = pd.read_csv(csv_path)
    if "t" in df.columns:
        t = pd.to_numeric(df["t"], errors="coerce").to_numpy(dtype=float)
    else:
        t = np.arange(1, len(df) + 1, dtype=float)

    rollout_cols = [col for col in df.columns if col != "t"]
    if not rollout_cols:
        raise ValueError("CSV has no rollout columns: %s" % csv_path)

    values = df[rollout_cols].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=float)
    if values.ndim != 2:
        raise ValueError("Unexpected CSV shape in %s" % csv_path)

    mean = np.nanmean(values, axis=1)

    if len(t) != len(mean) or np.isnan(t).any():
        t = np.arange(1, len(mean) + 1, dtype=float)

    return t, mean


def _group_label(group_index: int, group_slug: str, demand_manifest: Dict[int, str]) -> str:
    if group_index in demand_manifest:
        return demand_manifest[group_index]
    return group_slug


def _plot_metric_for_controller(
    controller_label: str,
    metric: str,
    series_by_group: Dict[int, RawSeriesFile],
    demand_manifest: Dict[int, str],
    save_path: Path,
) -> None:
    if not series_by_group:
        return

    plt.figure(figsize=(11, 6))

    for group_index in sorted(series_by_group):
        entry = series_by_group[group_index]
        t_axis, mean = _load_mean_series(entry.path)
        label = _group_label(group_index, entry.group_slug, demand_manifest)
        plt.plot(t_axis, mean, label=label)

    plt.xlabel("Simulation second")
    plt.ylabel(_metric_ylabel(metric))
    plt.title(_metric_title(controller_label, metric))
    plt.legend(ncol=2, fontsize=12)
    plt.tight_layout()

    save_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(save_path)
    plt.close()

    print("Saved:", save_path)


def main() -> None:
    args = parse_args()
    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()

    raw_files = _discover_raw_series(input_dir)
    controller_manifest = _read_controller_manifest(input_dir / "controller_manifest.csv")
    demand_manifest = _read_demand_manifest(input_dir / "demand_manifest.csv")

    selected_controllers = _resolve_selected_controllers(
        (item.controller for item in raw_files),
        args.controllers,
    )

    files_by_controller_and_metric: Dict[str, Dict[str, Dict[int, RawSeriesFile]]] = defaultdict(
        lambda: defaultdict(dict)
    )

    for item in raw_files:
        if item.controller not in selected_controllers:
            continue

        by_metric = files_by_controller_and_metric[item.controller][item.metric]
        if item.group_index in by_metric:
            existing = by_metric[item.group_index]
            preferred = min(existing.path, item.path)
            chosen = existing if existing.path == preferred else item
            skipped = item if chosen is existing else existing
            by_metric[item.group_index] = chosen
            warnings.warn(
                "Duplicate series for controller=%s metric=%s group=%02d. Keeping %s, skipping %s"
                % (
                    item.controller,
                    item.metric,
                    item.group_index,
                    chosen.path,
                    skipped.path,
                ),
                RuntimeWarning,
            )
            continue

        by_metric[item.group_index] = item

    generated = 0
    for controller in selected_controllers:
        controller_label = _label_for_controller(controller, controller_manifest)
        family = _family_for_controller(controller, raw_files, controller_manifest)
        target_family_dir = output_dir / family

        queue_files = files_by_controller_and_metric.get(controller, {}).get("queue", {})
        speed_files = files_by_controller_and_metric.get(controller, {}).get("speed", {})

        queue_path = target_family_dir / ("%s_queue_by_group.png" % controller)
        speed_path = target_family_dir / ("%s_speed_by_group.png" % controller)

        if queue_files:
            _plot_metric_for_controller(
                controller_label=controller_label,
                metric="queue",
                series_by_group=queue_files,
                demand_manifest=demand_manifest,
                save_path=queue_path,
            )
            generated += 1
        else:
            warnings.warn(
                "Skipping queue plot for %s (no queue raw CSV files found)." % controller,
                RuntimeWarning,
            )

        if speed_files:
            _plot_metric_for_controller(
                controller_label=controller_label,
                metric="speed",
                series_by_group=speed_files,
                demand_manifest=demand_manifest,
                save_path=speed_path,
            )
            generated += 1
        else:
            warnings.warn(
                "Skipping speed plot for %s (no speed raw CSV files found)." % controller,
                RuntimeWarning,
            )

    print("Controllers selected:", ", ".join(selected_controllers))
    print("Plots generated:", generated)


if __name__ == "__main__":
    main()
